name: Deploy Next.js to GitHub Pages

on:
  pull_request:
    branches:
      - main

  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x" # Node.jsのバージョン

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js app
        run: npm run build && npm run export # 静的サイトを出力

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # `next export`の出力ディレクトリ
